AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dakobed Rest API Service
Parameters:
  Region:
    Type: String
    Default: us-west-2
  QueueName:
    Type: String
    Default: LibrosaTransformsQueue
  BucketName:
    Type: String
    Default: dakobed-mir-upload-bucket
Resources:
  UploadApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: UploadApi
      StageName: Prod
      DefinitionUri: s3://dakobed-serverless-apis/1dae8c2e1b633149a48a8b56eae567fe
  Bucket:
    Type: AWS::S3::Bucket
    DependsOn:
    - ProcessingLambdaPermission
    Properties:
      BucketName:
        Ref: BucketName
      NotificationConfiguration:
        LambdaConfigurations:
        - Event: s3:ObjectCreated:*
          Function:
            Fn::GetAtt:
            - VerifyUploadFunction
            - Arn
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - HEAD
          - POST
          AllowedOrigins:
          - '*'
  PresignedPostUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      FunctionName: PresignedPostUploadFunction
      Policies:
      - S3CrudPolicy:
          BucketName:
            Ref: BucketName
      - SQSSendMessagePolicy:
          QueueName: InitiateTransformsQueue
      - AWSLambdaBasicExecutionRole
      - DynamoDBCrudPolicy:
          TableName: UserUploads
      CodeUri: s3://dakobed-serverless-apis/7c3a086099e2a2e854b5f3c5ce987744
      Handler: app.lambda_handler
      Runtime: python3.7
      Layers:
      - Fn::ImportValue: upload-authorization-layer-stack:AuthorizationLayer
      Environment:
        Variables:
          UploadBucket:
            Ref: BucketName
          userpool_id:
            Fn::ImportValue: upload-api-userpool-stack:UserPool
          app_client_id:
            Fn::ImportValue: upload-api-userpool-stack:UserPoolClient
          region:
            Ref: Region
      Events:
        UploadApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: UploadApi
            Path: /signedURL
            Method: POST
  GatewayInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - UploadApi
    - PresignedPostUploadFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: PresignedPostUploadFunction
      Principal: apigateway.amazonaws.com
  ProcessingLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: VerifyUploadFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:s3:::${BucketName}
      SourceAccount:
        Ref: AWS::AccountId
  ProcessingLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: allowLogging
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
      - PolicyName: getAndDeleteObjects
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:DeleteObject
            Resource:
              Fn::Sub: arn:aws:s3:::${BucketName}/*
  VerifyUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      FunctionName: VerifyUploadFunction
      CodeUri: s3://dakobed-serverless-apis/4685e9b5e9677e75ef93d3cd0a4bada1
      Handler: app.lambda_handler
      Runtime: python3.7
      Role:
        Fn::GetAtt:
        - ProcessingLambdaExecutionRole
        - Arn
Outputs:
  UploadApi:
    Description: API Gateway endpoint URL for Prod stage upload API
    Value:
      Fn::Sub: https://${UploadApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/signedURL
    Export:
      Name:
        Fn::Join:
        - ':'
        - - Ref: AWS::StackName
          - UploadApi
  Bucket:
    Description: API Gateway endpoint URL for Prod stage upload API
    Value:
      Ref: BucketName
    Export:
      Name:
        Fn::Join:
        - ':'
        - - Ref: AWS::StackName
          - Bucket
