AWSTemplateFormatVersion : "2010-09-09"
Transform: AWS::Serverless-2016-10-31


Parameters:
  KeyName:
    Type: String
    Default: corwin
  InstanceType:
    Type: String
    Default: t2.micro


Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e472933a1395e172
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install ec2-net-utils -y

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow http to client host
        SecurityGroupIngress:
        - IpProtocol: "-1"
#          FromPort: 80
#          ToPort: 80
          CidrIp: 0.0.0.0/0
