AWSTemplateFormatVersion : "2010-09-09"
Transform: AWS::Serverless-2016-10-31


Parameters:
  KeyName:
    Type: String
    Default: corwin
  InstanceType:
    Type: String
    Default: t2.micro


Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e472933a1395e172
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install libXcomposite libXcursor libXi libXtst libXrandr alsa-lib mesa-libEGL libXdamage mesa-libGL libXScrnSaver -y
          yum install python3 -y
          wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
          sh Anaconda3-2020.02-Linux-x86_64.sh

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow http to client host
        SecurityGroupIngress:
        - IpProtocol: "-1"
#          FromPort: 80
#          ToPort: 80
          CidrIp: 0.0.0.0/0
